### ISSUE TITLE
Please modify imports to reduce runtime impact

### ISSUE THREAD

**Issue by ofek** [hynek/stamina#31]
Start up time which is important for CLIs:

```
❯ python -m timeit -n 1 -r 1 "import structlog"
1 loop, best of 1: 185 msec per loop
❯ python -m timeit -n 1 -r 1 "from prometheus_client import Counter"
1 loop, best of 1: 97.2 msec per loop
```

RSS which is important for long-running processes on users' machines:

```
❯ python -c "import psutil;f=lambda p=psutil.Process(): print(p.memory_info().rss / 1024 ** 2);f();import structlog;f()"
14.984375
29.125
❯ python -c "import psutil;f=lambda p=psutil.Process(): print(p.memory_info().rss / 1024 ** 2);f();from prometheus_client import Counter;f()"
14.6796875
22.03515625
```

**Comment by hynek** [comment]
I'm confused, is this supposed to be here? You're benchmarking structlog & `prometheus_client` here?

**Comment by hynek** [comment]
Ah wait you want the instrumentation-detection code to be delayed? That might happen as part of the bigger instrumentation work in https://github.com/hynek/stamina/discussions/27

**Comment by ofek** [comment]
Yes basically it would be desirable for features that are not used to have no runtime impact. As it is, I cannot yet use this library 🙁
